import { getOrganizerEvents, createEvent, getOrganizerEventById, publishEvent, unpublishEvent, deleteEvent, cancelEvent, updateEvent } from "../controllers/event.controller";
import { getOrganizerShowsByEvent, publishShow, unpublishShow, cancelShow, createShow } from "../controllers/show.controller";
import { getOrganizerShowById } from "../controllers/show.controller";
import { streamAdminDashboard } from "../controllers/organizer-sse.controller";
import { createStaffAccount, getOrganizerStaffs, assignStaffToShow, removeStaffFromShow, getOrganizerDashboard, getOrganizerAnalyticsDashboard, getOrganizerCheckInHistory, getOrganizerStaffDetail } from "../controllers/organizer.controller";
import { getTicketTypesByShow, getTicketTypeById, updateTicketType, deleteTicketType } from "../controllers/ticket-type.controller";
import express from 'express';
const organizerRouter = express.Router();

organizerRouter.get('/events', getOrganizerEvents);
organizerRouter.post('/events', createEvent);
organizerRouter.get('/events/:event_id', getOrganizerEventById)
organizerRouter.post('/events/:event_id/shows', createShow);
organizerRouter.get('/events/:event_id/shows', getOrganizerShowsByEvent);
organizerRouter.get('/shows/:show_id', getOrganizerShowById);
organizerRouter.post('/shows/:show_id/publish', publishShow);
organizerRouter.post('/shows/:show_id/unpublish', unpublishShow);
organizerRouter.post('/shows/:show_id/cancel', cancelShow);
organizerRouter.post('/events/:event_id/publish', publishEvent);
organizerRouter.post('/events/:event_id/unpublish', unpublishEvent);
organizerRouter.delete('/events/:event_id', deleteEvent);
organizerRouter.post('/events/:event_id/cancel', cancelEvent);
organizerRouter.post('/staff', createStaffAccount);
organizerRouter.get('/staffs', getOrganizerStaffs);
organizerRouter.get('/staffs/:staff_id', getOrganizerStaffDetail);
organizerRouter.post('/shows/:show_id/assign-staff', assignStaffToShow);
organizerRouter.post('/shows/:show_id/remove-staff', removeStaffFromShow);
organizerRouter.get('/dashboard', getOrganizerAnalyticsDashboard);
organizerRouter.get('/dashboard/legacy', getOrganizerDashboard);
organizerRouter.get('/check-ins', getOrganizerCheckInHistory);
organizerRouter.get('/events/:event_id/sse/dashboard/:show_id', streamAdminDashboard);
organizerRouter.get('/sse/dashboard/:show_id', streamAdminDashboard);
organizerRouter.put('/events/:event_id', updateEvent);
organizerRouter.get("/shows/:show_id/ticket-types", getTicketTypesByShow);
organizerRouter.get("/shows/:show_id/ticket-types/:ticketTypeId", getTicketTypeById);
organizerRouter.put("/shows/:show_id/ticket-types/:ticketTypeId", updateTicketType);
organizerRouter.delete("/shows/:show_id/ticket-types/:ticketTypeId", deleteTicketType);
export default organizerRouter;