import * as dotenv from "dotenv";
dotenv.config();

const { URI, PORT, SECRET_ACCESS_TOKEN, REDIS_URL, RSA_PRIVATE_KEY, REDIS_PASSWORD, REDIS_HOST, REDIS_PORT, JWT_SECRET, MOCK_PAYMENT_SECRET, FRONTEND_URL, BACKEND_URL } = process.env;

export { URI, PORT, SECRET_ACCESS_TOKEN, REDIS_URL, RSA_PRIVATE_KEY, REDIS_PASSWORD, REDIS_HOST, REDIS_PORT, JWT_SECRET, MOCK_PAYMENT_SECRET, FRONTEND_URL, BACKEND_URL };